### ISSUE TITLE
ppa:jonathonf/python-3.6 is no longer available from public access

### ISSUE THREAD

**Issue by sowizdrzal** [CLARIN-PL/PolDeepNer#12]
```
W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Hi,
I try to build docker, but I came across a problem with ppa:jonathonf/python-3.6 is no longer available from public access. Is there any hope that will be fixed or do you know any repo which will work instead? I decided to write here before contacting jonathonf because I didn't know if you were aware of the current situation.

**Comment by mczuk** [comment]
The Dockerfile was updated to ubuntu18.04 and it should work now.
