### ISSUE TITLE
Training models using custom data 

### ISSUE THREAD

**Issue by LukGerman** [CLARIN-PL/PolDeepNer#4]
I would like to improve PolDeepNer performance on some texts by training models using my custom domain data. How do you generate your data?

Can you suggest any tools assuming data that I have at my disposal is in a Stanford format, like in the example below:
```
She     O
works    O
on O
C#     TECHNOLOGY
at O
New   ORGANIZATION
York  ORGANIZATION
Times   ORGANIZATION
```

**Comment by mczuk** [comment]
You have to convert the data into IOB format, .i.e. 
```
She     O
works   O
on      O
C#      B-TECHNOLOGY
at      O
New     B-ORGANIZATION
York    I-ORGANIZATION
Times   I-ORGANIZATION
```

Assuming that in the input file the columns are separated with tabs you can use this script https://github.com/mczuk/ENERT/blob/master/scripts/io2iob.py
