### ISSUE TITLE
Loading model fails

### ISSUE THREAD

**Issue by LukGerman** [CLARIN-PL/PolDeepNer#6]
After completing all preparation steps, defined in docs, evaluation and processing fails with following error:

```
Model file cannot be opened for loading!
Traceback (most recent call last):
  File "core/interactive_test.py", line 12, in <module>
    ner = PolDeepNer("model")
  File "/poldeepner/core/poldeepner.py", line 13, in __init__
    self.models.append(Sequence.load(os.path.join(model, "poldeepner-nkjp-ftcc-bigru"), os.path.join(model, "cc.pl.300.bin")))
  File "/poldeepner/core/wrapper.py", line 168, in load
    self.p = VectorTransformer.load(preprocessor_file, fasttext)
  File "/poldeepner/core/preprocessing.py", line 94, in load
    p.load_fasttext(fasttext_path)
  File "/poldeepner/core/preprocessing.py", line 81, in load_fasttext
    self.fasttext = FastText(fasttext_path)
  File "src/pyfasttext.pyx", line 194, in pyfasttext.FastText.__cinit__
  File "src/pyfasttext.pyx", line 664, in pyfasttext.FastText.load_model
RuntimeError: fastext tried to exit: 1
```

Here are dependencies with versions that are currently installed during docker build:

```absl-py==0.7.1
astor==0.7.1
cysignals==1.10.2
Cython==0.29.6
fasttext==0.8.3
future==0.17.1
gast==0.2.2
grpcio==1.19.0
h5py==2.9.0
Keras==2.2.4
Keras-Applications==1.0.7
keras-contrib==2.0.8
Keras-Preprocessing==1.0.9
Markdown==3.0.1
mock==2.0.0
nltk==3.4
numpy==1.16.2
pbr==5.1.3
protobuf==3.7.0
pyfasttext==0.4.6
python-dateutil==2.8.0
PyYAML==5.1
scikit-learn==0.20.3
scipy==1.2.1
seqeval==0.0.6
singledispatch==3.4.0.3
six==1.12.0
sklearn==0.0
tensorboard==1.13.1
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
termcolor==1.1.0
Werkzeug==0.15.1
```

I think there might be a problem with current versions of dependencies, that were not existing during last commit. Could you share versions that you were using?

**Comment by MichalGawor** [comment]
Are you sure that cc.pl.300.bin exists in 'poldeepner/data/model/'?

**Comment by LukGerman** [comment]
No, it doesn't. Also in `poldeepner/model`, there is only `cc.pl.300.bin.gz` file with 0 bytes. I've just restarted `download_unpack.sh` and it seems that I don't have a permission to fetch this file. Here is a log from the script run:

```
--2019-03-25 13:10:47--  https://s3-us-west-1.amazonaws.com/fasttext-vectors/word-vectors-v2/cc.pl.300.bin.gz
Resolving s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)... 54.231.237.37
Connecting to s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)|54.231.237.37|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-03-25 13:10:48 ERROR 403: Forbidden.

- cc.pl.300.bin.gz downloaded

gzip: /home/luk/Projects/pol_deep_ner/poldeepner/model/cc.pl.300.bin.gz: unexpected end of file
- cc.pl.300.bin.gz unpacked
--2019-03-25 13:10:48--  https://nextcloud.clarin-pl.eu/index.php/s/HIFaRv7ekgw24F1/download
```

@MichalGawor Are you able to set public read for this file?

**Comment by mczuk** [comment]
We do not own the `cc.pl.300.bin.gz` file. It looks like the authors moved it here https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.pl.300.bin.gz. The complete list of factText model build on Common Crawl can be found here https://fasttext.cc/docs/en/crawl-vectors.html. We will have to update the link in the `download_unpack` script.

**Comment by mczuk** [comment]
OK, the link has been updated in the `download_unpack`. Now it should work.

**Comment by LukGerman** [comment]
Ok, thanks for fast response. I really appreciate your work, guys! :)

If I can suggest something in this topic, IMO `download_unpack.sh` should fail if required file is not available.
