### ISSUE TITLE
How do I infer data on my dataset?

### ISSUE THREAD

**Issue by thak123** [CLARIN-PL/PolDeepNer#7]
which script or command should be used to get the model tag an existing text  ?

**Comment by thak123** [comment]
python3.6 core/process_poleval.py \
            -i data/poleval2018ner-data/index_iob.list \
            -o data/poldeepner-output.json \
            -m model



How to reproduce the figures from the readme ?

which model and which embeddings should be used

**Comment by mczuk** [comment]
> which script or command should be used to get the model tag an existing text ?

I have made a larger update and some more new scripts and models were added to the main branch.

To process a single file use the following command:

`python poldeepner/core/process_file.py -m nkjp-poleval18 -i poldeepner/data/kpwr-toronto.txt`

If you need to process a batch of file than I suggest to write a custom script to do it, based on the the above.

**Comment by mczuk** [comment]
> python3.6 core/process_poleval.py
> -i data/poleval2018ner-data/index_iob.list
> -o data/poldeepner-output.json
> -m model
> 
> How to reproduce the figures from the readme ?
> 
> which model and which embeddings should be used

To reproduce the evaluation results just run the following:

Generate json file for the evaluation corpus:

```
python poldeepner/core/process_poleval.py \
            -i poldeepner/data/poleval2018ner-data/index_iob.list \
            -o poldeepner/data/poldeepner-output.json \
            -m nkjp-poleval18
```
Run the official evaluation script:

```
python poldeepner/core/poleval_ner_test.py \
             -g poldeepner/data/POLEVAL-NER_GOLD.json \
             -u poldeepner/data/poldeepner-output.json
```
Definition of the models can be found in https://github.com/CLARIN-PL/PolDeepNer/blob/master/poldeepner/core/pretrained.py

README.md also contains scripts to retrain the model. Keep in mind that the retrain model might have different performance, as training is not deterministic.
